version: '3'
services:
  web:
    build: .
    ports:
      - "5601:5601"
      - "5000:5000"
#    volumes:
#      - .:/code
    environment:
      FLASK_ENV: development
#  redis:
#    image: "redis:alpine"
