version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
      # - "3000:3000"
    environment:
      TZ: America/Toronto
      FLASK_ENV: development
    # volumes:
      # - ./:/usr/src/app